#!/usr/bin/env fish --no-config

# The hook is given three parameters:
# 1) the ref of the previous HEAD,
set previous_head $argv[1]
# 2) the ref of the new HEAD (which may or may not have changed), and
set new_head $argv[2]
# 3) a flag indicating whether the checkout was a branch checkout (changing branches, flag=1) or a file checkout (retrieving a file from the index, flag=0).
set flag $argv[3]

function file_changed -a filename
  # We can't just use word boundaries (`\b`) around the $filename because if passed "git", that
  # would match "tag-git/bin/git-shalector", which doesn't have a file named git
  git diff --name-only $previous_head $new_head | rg -q '(^|/)\b'$filename'(/|$)'
end

if file_changed Gemfile
  if bundle check > /dev/null || bundle install --jobs=4
    bundle config set bin './bin/stubs'
    bundle binstubs --all 2>&1 | rg -v 'Bundler itself does not use binstubs because its version is selected by RubyGems'
  else
    echo "Would have run bundle, but skipped"
  end
else if file_changed yarn.lock
  yarn install
else if file_changed pnpm-lock.yaml
  pnpm install
else if file_changed package-lock.json
  npm install
end
