#!/bin/sh

set -e

git_root=$(git rev-parse --show-toplevel)
echo "Installing Git hooks..."
[ -f .git/hooks/post-merge ] && rm .git/hooks/post-merge
ln -s "$git_root"/tag-git/hooks/dotfiles-post-merge "$git_root"/.git/hooks/post-merge
