#!/bin/sh

# Take a picture on wakeup
# To actually run it on wakeup, download SleepWatcher from
# http://www.bernhard-baehr.de/
# And follow the instructions on how to create a launchd file.
# Copy the launchd file to ~/Library/LaunchAgents
# Run: launchd load ~/Library/LaunchAgents/your-file.plist
# Run: launchd start ~/Library/LaunchAgents/your-file.plist to manually start
# it (it'll start at boot, but you want it NOW)

# And you're done!

# isightcapture comes from http://www.intergalactic.de/pages/iSight.html
# Creates a picture named like 2011-04-01_01_24_23.jpg
# It chokes on anything with a colon in it.
mkdir -p ~/snapshots
isightcapture -w 800 -h 600 ~/snapshots/$(date +%F_%H_%M_%S).jpg
