#!/usr/bin/env ruby
# From https://github.com/tsaleh/dotfiles/blob/master/vim/update_bundles

# Ragel doesn't have a git repo or vim script, it's just hosted by the Ragel
# maintainer.
RAGEL_URL = 'http://www.complang.org/ragel/ragel.vim'
RAGEL_FILE = 'ragel/syntax/ragel.vim'

git_bundles = [ 
  #"git://github.com/astashov/vim-ruby-debugger.git",
  #"git://github.com/godlygeek/tabular.git",
  #"git://github.com/hallison/vim-rdoc.git",
  #"git://github.com/pangloss/vim-javascript.git",
  #"git://github.com/scrooloose/nerdtree.git",
  #"git://github.com/timcharper/textile.vim.git",
  #"git://github.com/tpope/vim-repeat.git",
  #"git://github.com/tpope/vim-surround.git",
  #"git://github.com/tpope/vim-vividchalk.git",
  #"git://github.com/tsaleh/vim-matchit.git",
  #"git://github.com/tsaleh/vim-supertab.git",
  #"git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/vim-ruby/vim-ruby.git",
]

vim_org_scripts = [
  # http://www.vim.org/scripts/script.php?script_id=1682
  # 7062: v070503
  #["IndexedSearch", "7062",  "plugin"],
  # http://www.vim.org/scripts/script.php?script_id=2423
  # 14204: v4.5
  #["gist",          "14204", "plugin"],
  # http://www.vim.org/scripts/script.php?script_id=2416
  # 12276: v0.4
  ["jquery",        "12276", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

FileUtils.mkdir_p("ragel/syntax")
File.open(RAGEL_FILE, 'w') do |file|
  file << open(RAGEL_URL).read
end

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

