#!/bin/sh
#
# Called by "git commit" with no arguments.
# The hook should exit with non-zero status after issuing an appropriate message
# if it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff --cached | grep "show me the page" &>/dev/null

if [ $? == 0 ]; then
  echo "Please remove a stray 'show me the page'."
  exit 1
fi
