"$schema" = 'https://starship.rs/config-schema.json'
# ANSI colors for fg:NUMBER
# https://i.stack.imgur.com/KTSQa.png

# Don't print a new line at the start of the prompt
add_newline = false

format = """
[](fg:lavender)\
$time\
[](bg:pink fg:lavender)\
$directory\
[](bg:blue fg:pink)\
$ruby\
$rust\
$nodejs\
$java\
$python\
[](bg:green fg:blue)\
$git_branch\
$git_status\
[](fg:green)\
$line_break\
$character"""

# See more palettes at the bottom of this file
palette = 'catppuccin_macchiato'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:pink fg:crust"
format = "[ $path ]($style)"
home_symbol	= '~'
# The number of parent folders that the current directory should be truncated to.
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[directory.substitutions]
# Light text
"Documents" = "󰈙 "
# Dark text
color_fg1 = "#11111b"  # crust from catpuccin_mocha
"Downloads" = " "
color_bg3 = '#665c54'
"Music" = "󰝚 "
color_aqua = '#689d6a'
"Pictures" = " "
color_orange = '#fe8019'
"Developer" = "󰲋 "
color_red = '#fb4934'
color_yellow = '#d79921'

[time]
disabled = false
# https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
time_format = "%A %I:%M %p"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'
use_12hr = true

[git_branch]
symbol = ""
style = "fg:crust bg:green"
truncation_length = 20
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:crust bg:green"
format = '([\[$all_status\]]($style))[( $ahead_behind )]($style)'
modified = "[M](italic fg:red bg:green)"
stashed = "[S](fg:crust bg:green)"

[nodejs]
symbol = ""
style = "fg:crust bg:blue"
format = '[ $symbol( $version) ]($style)'
version_format = "$major"
detect_files = ["package.json", ".node-version", "yarn.lock"]
detect_folders = ["node_modules"]
# Unlike the standard nodejs module, it intentionally does not check for
# *.js or *.ts since that triggers too often
detect_extensions = []

[ruby]
symbol = "💎"
style = "fg:crust bg:blue"
format = '[ $symbol( $version) ]($style)'
# Show ruby version in my home directory
detect_folders = ["Desktop"]
[java]
symbol = " "
style = "fg:crust bg:blue"
format = '[ $symbol($version)]($style)'

[python]
symbol = ""
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[time]
disabled = false
# https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
time_format = "%A %I:%M %p"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
# 0: no truncation
error_symbol = '[❯](bold fg:red)'
# 2: show 1 parent directory, etc
vimcmd_symbol = '[❮](bold fg:green)'
style = "fg:color_fg1 bg:color_yellow"
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'
truncate_to_repo = true

[git_branch]
format = "[($symbol$branch )]($style)"
style = "bg:color_blue"
truncation_length = 40

[git_state]
format = "[\\($state( $progress_current/$progress_total)\\) ]($style)"
style = "bg:color_blue"
cherry_pick = "[🍒](fg:color_red bg:color_blue)"

[git_status]
format = """[(\\[\
$conflicted\
($stashed)\
($deleted )\
$modified\
$staged\
$untracked\
$typechanged\
$renamed\
\\] )\
$ahead_behind\
](bg:color_blue)"""
# $all_status = $conflicted $stashed $delete

[cmd_duration]
show_milliseconds = true
format = " took $duration "
style = "bg:lavender"
disabled = false
min_time_to_notify = 10_000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#D70040"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
