"$schema" = 'https://starship.rs/config-schema.json'
# ANSI colors for fg:NUMBER
# https://i.stack.imgur.com/KTSQa.png

# Don't print a new line at the start of the prompt
add_newline = false

format = """
[](color_aqua)\
$ruby\
$nodejs\
$java\
$directory\
[](bg:color_blue fg:color_yellow)\
$git_branch\
$git_state\
$git_status\
[ ](fg:color_blue bg:color_purple)\
[\\$](bg:color_purple fg:color_fg1)\
[ ](color_purple)"""

right_format = """
$time
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
# Light text
color_fg0 = '#fbf1c7'
# Dark text
color_fg1 = "#11111b"  # crust from catpuccin_mocha
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#fe8019'
color_purple = '#b16286'
color_red = '#fb4934'
color_yellow = '#d79921'

[time]
disabled = false
format = "[$time]($style) "
style = "#888888"
use_12hr = true

[ruby]
format = "[💎($version )]($style)"
version_format = "$major.$minor"
style = "bg:color_aqua fg:color_fg0"
# Show ruby version in my home directory
detect_folders = ["Desktop"]

[nodejs]
version_format = "$major"
detect_files = ["package.json", ".node-version", "yarn.lock"]
detect_folders = ["node_modules"]
# Unlike the standard nodejs module, it intentionally does not check for
# *.js or *.ts since that triggers too often
detect_extensions = []
symbol = "📦"
format = "[($symbol$version )]($style)"
style = "bg:color_aqua fg:color_fg0"

[java]
format = "[$symbol$version ]($style)"
symbol = '☕'
version_format = "$major"
style = "bg:color_aqua fg:color_fg0"
detect_extensions = ["java"]
detect_folders = ["loquat"]

[directory]
# Show (n-1) parent directories
# 0: no truncation
# 1: basename $PWD
# 2: show 1 parent directory, etc
truncation_length = 2
style = "fg:color_fg1 bg:color_yellow"
format = "[ ](bg:color_yellow fg:color_aqua)[$path ]($style)"
# When in a Git repo, should we keep showing parent directories?
truncate_to_repo = true

[git_branch]
format = "[($symbol$branch )]($style)"
style = "bg:color_blue"
truncation_length = 15

[git_state]
format = "[\\($state( $progress_current/$progress_total)\\) ]($style)"
style = "bg:color_blue"
cherry_pick = "[🍒](fg:color_red bg:color_blue)"

[git_status]
format = """[(\\[\
$conflicted\
($stashed )\
($deleted )\
$modified\
$staged\
$untracked\
$typechanged\
$renamed\
\\] )\
$ahead_behind\
](bg:color_blue)"""
# $all_status = $conflicted $stashed $deleted $renamed $modified $typechanged $staged $untracked
# except $all_status doesn't have spaces
conflicted = "[=](bold color_red bg:color_blue)"
stashed = '[\$$count](bold fg:color_yellow bg:color_blue)'
deleted = "[✘$count](bold fg:color_red bg:color_blue)"
renamed = "[»](bold color_fg0 bg:color_blue)"
modified = "[M$count](bold fg:color_fg0 bg:color_blue)"
staged = "[S$count](bold fg:color_orange bg:color_blue)"
untracked = "[?$count](bold color_fg0 bg:color_blue)"

behind = "[↓](bold fg:color_fg0 bg:color_blue)"
ahead = "[↑](bold fg:color_fg0 bg:color_blue)"
up_to_date = "[✓](bold fg:color_fg0 bg:color_blue)"

diverged = "[⇔](bold fg:color_red bg:color_blue)"
