#!/bin/bash

set -e

if ! asdf plugin-list | grep -qF ruby; then
  echo 'Installing ASDF Ruby plugin...'
  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
fi

if command -v rbenv &>/dev/null; then
  echo 'Migrating from rbenv -> asdf...'

  if rbenv versions 2>/dev/null | grep -qFv system; then
    echo 'Migrating rubies from rbenv -> asdf...'
    mkdir -p /usr/local/opt/asdf/installs/ruby
    mv ~/.rbenv/versions/* /usr/local/opt/asdf/installs/ruby/
  fi

  echo 'Removing ~/.rbenv...'
  rm -rf ~/.rbenv

  echo 'Uninstalling rbenv...'
  brew uninstall rbenv-default-gems
  brew uninstall rbenv
fi

latest_ruby_version(){
  asdf list-all ruby | grep -vE 'preview|rc' | tail -1
}

echo "Installing latest Ruby (version $(latest_ruby_version))..."
asdf install ruby "$(latest_ruby_version)"
asdf global ruby "$(latest_ruby_version)"
