#!/bin/bash

set -e

latest_ruby_version(){
  rbenv install -l 2>/dev/null | rg '^\d' | tail -1
}

echo "Installing latest Ruby (version $(latest_ruby_version))..."
rbenv install "$(latest_ruby_version)"
rbenv global "$(latest_ruby_version)"
