#!/bin/bash

set -e

if ! asdf plugin-list | grep -qF nodejs; then
  echo 'Installing ASDF NodeJS plugin...'
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
fi

if command -v nvm &>/dev/null; then
  echo 'Migrating from NVM -> asdf...'

  echo 'Uninstalling NVM...'
  brew uninstall nvm
fi

if brew list yarn &>/dev/null; then
  echo "Uninstalling Homebrew's Yarn because we can't use a specific version..."
  brew uninstall yarn
fi

echo 'Installing NodeJS and Yarn...'
# Hired's version of Node
asdf install nodejs 8.10.0
asdf global nodejs 8.10.0
# Hired's version of Yarn
npm install -g https://yarnpkg.com/downloads/1.6.0/yarn-v1.6.0.tar.gz
